### ISSUE TITLE
Uninstalling breaks flake8

### ISSUE THREAD

**Issue by Dreamsorcerer** [ayivima/flake8-lineleak#2]
After pip uninstalling the plugin, flake8 is broken as it still tries to load the plugin.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flake8/plugins/manager.py", line 158, in load_plugin
    self._load()
  File "/usr/local/lib/python3.7/site-packages/flake8/plugins/manager.py", line 135, in _load
    self._plugin = self.entry_point.load()
  File "/usr/local/lib/python3.7/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lineleak'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".git/hooks/pre-commit", line 10, in <module>
    lazy=git.config_for('lazy'),
  File "/usr/local/lib/python3.7/site-packages/flake8/main/git.py", line 46, in hook
    app.initialize(["."])
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 363, in initialize
    self.find_plugins()
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 199, in find_plugins
    self.check_plugins.load_plugins()
  File "/usr/local/lib/python3.7/site-packages/flake8/plugins/manager.py", line 410, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/usr/local/lib/python3.7/site-packages/flake8/plugins/manager.py", line 297, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flake8/plugins/manager.py", line 408, in load_plugin
    return plugin.load_plugin()
  File "/usr/local/lib/python3.7/site-packages/flake8/plugins/manager.py", line 165, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "LL" due to No module named 'lineleak'.
```

**Comment by Dreamsorcerer** [comment]
OK, seems there was a `~lake8_lineleak-1.0.2.dist-info` file left in the path. Not sure what that is about.

**Comment by ayivima** [comment]
Looking into this @Dreamsorcerer. Thanks.
